demo3/blog/urls.py
from django.conf.urls import url
from . import views
from .feed import ArticleFeed
from haystack.views import SearchView
app_name = "blog"

urlpatterns = [
    # url(r'^$', views.IndexView.as_view(),name="index"),
    url(r'^$', views.index,name="index"),
    url(r'^single/(\d+)/$',views.SingleView.as_view(),name="single"),
    url(r'^archives/(\d+)/(\d+)/$',views.ArchieveView.as_view(),name="archives"),
    url(r'^category/(\d+)/$',views.CategoryView.as_view(),name="category"),
    url(r'^tags/(\d+)/$',views.TagView.as_view(),name="tags"),
    url(r'^contact/$',views.ContactView.as_view(),name="contact"),
    url(r'^rss/$',ArticleFeed(),name="rss"),

    url(r'^sendmail/$',views.SendMailView.as_view(),name="sendmail"),
    url(r'^search/$',SearchView(),name="search")

]

demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('blog.urls',namespace="blog")),
]

demo3/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.

class Tag(models.Model):
    """
    标签表：与文章表存在多对多
    title：标题标签
    """
    title = models.CharField(max_length=20,)

    def __str__(self):
        return self.title

class Category(models.Model):
    """
    分类表：与文章存在一对多
    title：分类标题
    """
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Article(models.Model):
    """
    文章表：与标签表多对多， 与分类表多对一
    """
    title = models.CharField(max_length=30)
    body = models.TextField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    create_time = models.DateTimeField(auto_now=True)
    update_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Ads(models.Model):
    """
    轮播图模型类
    pic 字段为图片类型 upload_to 图片上传位置，数据中存储图片路径
    """
    pic = models.ImageField(upload_to="ads")
    desc = models.CharField(max_length=20)
    url = models.CharField(max_length=20)

    def __str__(self):
        return self.desc


class MessageInfo(models.Model):
    """
    联系我们页面内容
    """
    email = models.EmailField()
    # TextField不具备格式 使用富文本替换
    # info = models.TextField()
    info = HTMLField()

    def __str__(self):
        return self.email

demo3/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.views.generic import View,ListView,DetailView
from .models import *
from comments.forms import CommentForms
from comments.models import Comment
from django.http import HttpResponse
from django.core.paginator import Paginator
import markdown
from django.core.mail import send_mail,EmailMultiAlternatives
from demo3 import settings
from django.views.decorators.cache import cache_page
# Create your views here.

def getpageinfo(request, queryset, perpage, path):
    """
    返回页面
    :param request: 请求
    :param queryset: 分页对象列表
    :param perpage: 每页显示个数
    :param path: 路径
    :return:
    """
    paginator = Paginator(queryset,perpage)
    pagenum = request.GET.get("page")
    pagenum = 1 if pagenum == None else pagenum
    page = paginator.get_page(pagenum)
    page.path = path
    return page


class IndexView(View):
    """
    文章列表页视图类
    """

    @cache_page(60*5)
    def get(self,req):
        """
        重写get请求
        :param req:
        :return:
        """

        # articles = Article.objects.all()
        # latestarticles = articles.order_by("-create_time")[:3]

        # # 得到分页
        # paginator = Paginator(articles,2)
        # print(paginator.count)
        # print(paginator.object_list)
        # print(paginator.num_pages)
        # print(paginator.page_range)
        # # 得到页面
        # page = paginator.get_page(2)
        # print(page.object_list)
        # # 由页面得到分页    分页可以得到页面  页面可以得到分页
        # print(page.paginator)
        # print(page.number)
        # print(paginator is page.paginator)


        # paginator = Paginator(articles,1)
        # pagenum = req.GET.get("page")
        # pagenum = 1 if pagenum == None else pagenum
        # page = paginator.get_page(pagenum)
        # page.path = "/"

        articles = Article.objects.all()
        page = getpageinfo(req,articles,2,"/")
        return render(req,"blog/index.html",{"page":page})

        # return render(req,"blog/index.html",locals())

# @cache_page(60*5)
def index(req):
    articles = Article.objects.all()
    page = getpageinfo(req, articles, 2, "/")
    return render(req, "blog/index.html", {"page": page})


class SingleView(View):
    """
    文章详情页视图
    """
    def get(self,req,id):
        """
        重写get请求
        :param req:
        :param id:  文章id
        :return:
        """
        # article = Article.objects.get(pk=id)
        article = get_object_or_404(Article, pk=id)

        # 1获取markdown实例
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        # 2 使用markdown实例渲染指定字段
        article.body = md.convert(article.body)
        # 3 将md的目录对象赋予 article
        article.toc = md.toc

        # 向详情页面传递一个评论表单
        cf = CommentForms()
        # latestarticles = Article.objects.all().order_by("-create_time")[:3]
        return render(req,"blog/single.html",locals())

    def post(self,req,id):
        # 通过req.POST初始化一个有数据的cf对象
        cf=CommentForms(req.POST)
        # 如果表单里数据有效
        if cf.is_valid():
            # 通过cf的save方法得到模型类（Comment的实例）/暂时不保存数据库
            res = cf.save(commit=False)
            # 给模型类实例赋值
            res.article = get_object_or_404(Article,pk=id)
            # 给评论表中的文章赋值后才可以保存
            res.save()
            return redirect(reverse('blog:single',args=(id,)))


class ArchieveView(View):
    """
    归档视图
    """
    def get(self,req,year,month):
        articles = Article.objects.filter(create_time__year = year, create_time__month = month)

        # paginator = Paginator(articles,1)
        # pagenum = req.GET.get("page")
        # pagenum = 1 if pagenum == None else pagenum
        # page = paginator.get_page(pagenum)
        # page.path = "/archives/%s/%s/" % (year,month)

        page = getpageinfo(req, articles, 1, "/archives/%s/%s/" % (year,month))
        return render(req, "blog/index.html", {"page":page})

class CategoryView(View):
    """
    分类视图
    """
    def get(self,req,id):
        # category = get_object_or_404(Category,pk=id)
        # articles = category.article_set.all()
        # paginator = Paginator(articles, 1)
        # pagenum = req.GET.get("page")
        # pagenum = 1 if pagenum == None else pagenum
        # page = paginator.get_page(pagenum)
        # page.path = "/category/%s/" % (id,)

        articles = get_object_or_404(Category,pk=id).article_set.all()
        page = getpageinfo(req, articles,1, "/category/%s/" % (id,))
        return render(req, "blog/index.html", locals())

class TagView(View):
    """
    标签云视图
    """
    def get(self,req,id):
        # tag = get_object_or_404(Tag,pk=id)
        # articles = tag.article_set.all()
        # paginator = Paginator(articles, 1)
        # pagenum = req.GET.get("page")
        # pagenum = 1 if pagenum == None else pagenum
        # page = paginator.get_page(pagenum)
        # page.path = "/tags/%s/" % (id,)

        articles = get_object_or_404(Tag,pk=id).article_set.all()
        page = getpageinfo(req, articles,1, "/tags/%s/" % (id,))
        return render(req, "blog/index.html", locals())


class ContactView(View):
    def get(self,req):
        return render(req,"blog/contact.html")

    def post(self,req):
        email = req.POST.get("email")
        message = req.POST.get("message")

        info = MessageInfo()
        info.email = email
        info.info = message
        info.save()

        return  HttpResponse("建议成功")


class SendMailView(View):
    def get(self,req):
        # "发送邮件"
        try:
            # send_mail("测试邮件","正文",settings.DEFAULT_FROM_EMAIL, ["18137128152@163.com","599954453@qq.com"])
            # send_mail("测试邮件"," <h1>  <a href = 'http://www.baidu.com'> 百度 </a>  </h1> ",settings.DEFAULT_FROM_EMAIL, ["hxh15638129798@163.com","599954453@qq.com"])
            mail = EmailMultiAlternatives(subject="测试邮件html格式",body="<h1>  <a href = 'http://www.baidu.com'> 百度 </a>  </h1>", from_email=settings.DEFAULT_FROM_EMAIL,to= ["hxh15638129798@163.com","599954453@qq.com"])
            mail.content_subtype = "html"
            mail.send()

            return HttpResponse("发送成功")
        except:
            return HttpResponse("发送失败")

demo3/templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo3/templates/blog/base.html
{% load my_fun %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}    {% endblock %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" placeholder="搜索" required name="q">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block right %}

                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getlatestarticles as latestarticles%}
                        {% for article in latestarticles %}
                        <li>
                            <a href="{% url 'blog:single' article.id %}">{{ article.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getarchives as archives %}
                        {% for a in archives %}
                        <li>
                            <a href="{% url 'blog:archives' a.year a.month %}">{{ a.year }} 年 {{ a.month }} 月</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategorys as categorys %}
                        {% for category in categorys %}
                            <li>
                                <a href="{% url 'blog:category' category.id %}">{{category.title}} <span class="post-count">({{category.article_set.count}})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {% for tag in tags %}
                        <li>
                            <a href="{% url 'blog:tags' tag.id %}">{{ tag.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">HXH的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

demo3/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css">
		<link rel="stylesheet" href="/static/css/ionicons.min.css">
		<link rel="stylesheet" href="/static/css/pace.css">
	    <link rel="stylesheet" href="/static/css/custom.css">

	    <!-- js -->
	    <script src="/static/js/jquery-2.1.3.min.js"></script>
	    <script src="/static/js/bootstrap.min.js"></script>
	    <script src="/static/js/pace.min.js"></script>
	    <script src="/static/js/modernizr.custom.js"></script>

		<script type="text/javascript" src='/static/tiny_mce/tiny_mce.js'></script>
		<script type="text/javascript">
		tinyMCE.init({
		'mode':'textareas',
		'theme':'advanced',
		'width':'100%',
		'height':400
		});
		</script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'blog:contact' %}" method="post" class="contact-form">
									{% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="email" name="email" placeholder="Email" required>
											<textarea name="message" rows="7" placeholder="Your Message"></textarea>
<!--											<button type="submit" class="btn-send btn-5 btn-5b ion-ios-paperplane"><span></span></button>-->
											<input type="submit" value="Drop Me a Line">
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="/static/js/script.js"></script>
		
	</body>
</html>

demo3/templates/blog/index.html
{% extends "blog/base.html" %}
{% load my_fun %}
{% load cache %}

{% block title %}
    文章列表
{% endblock %}

{% block left %}
{% cache 300 carousel %}
{% getads as ads %}
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">

      {% for a in ads %}
        {% if forloop.counter == 1 %}
            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}" class="active"></li>
        {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter0}}"></li>
        {% endif %}
      {% endfor %}

  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

        {% for a in ads %}
        {% if forloop.counter == 1 %}
        <div class="item active">
            <img src="/static/media/{{ a.pic }}" alt="...">
            <div class="carousel-caption">
                <h1>{{ a.desc }}</h1>
            </div>
        </div>
        {% else %}
        <div class="item">
            <img src="/static/media/{{ a.pic }}" alt="...">
            <div class="carousel-caption">
                <h1>{{ a.desc }}</h1>
            </div>
        </div>
        {% endif %}
      {% endfor %}
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endcache %}

    {% for article in page.object_list %}
        <article class="post post-{{article.id}}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{% url 'blog:single' article.id %}">{{article.title}}：前言</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ article.category.title }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="2012-11-09T23:15:57+00:00">{{article.create_time}}</time></a></span>
                                <span class="post-author"><a href="#">{{article.author.username}}</a></span>
                                <span class="comments-link"><a href="#">{{article.comment_set.count}} 评论</a></span>
                                <span class="views-count"><a href="#">{{article.views}} 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{article|truncatechars:5}}...</p>
                            <div class="read-more cl-effect-14">
                                <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
    {% endfor %}


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        {% if page.has_previous %}
                            <li><a href="{{ page.path }}?page={{ page.previous_page_number }}">上一页</a></li>
                        {% endif %}


                        {% for i in page.paginator.page_range %}
                            {% if i == page.number %}
                            <li class="current"><a href="#">{{ i }}</a></li>
                            {% else %}
                            {{ page.new }}
                            <li><a href="{{ page.path }}?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}


                        {% if page.has_next %}
                            <li><a href="{{ page.path }}?page={{ page.next_page_number }}">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>

{% endblock %}